version: '3'

tasks:
  default:
    desc: "The default task" 
    cmds:
      - CGO_ENABLED=0 go build -o traefik-provider-frp main.go
      - scp traefik-provider-frp imini800-lab.lan:/tmp/traefik-provider-frp